# Generated by Django 4.2.1 on 2023-07-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_created_todo_updated_alter_todo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
